version: '3.1'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: denario_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data